services:
  core:
    build:
      dockerfile: Dockerfile
    image: wiseflow:latest
    tty: true
    stdin_open: true
    entrypoint: ["bash", "/app/run_all.sh"]
    ports:
      - 8090:8090
      - 8077:8077
    volumes:
      - ./core:/app